# This file was auto-generated by Polybuild

include_path_flag := -I
library_path_flag := -L
obj_path_flag := -o
out_path_flag := -o
library_flag := -l
static_flag := -static
shared_flag := -shared -fPIC
compile_only_flag := -c
obj_ext := .o
ifeq ($(OS),Windows_NT)
	include_path_flag := /I
	library_path_flag := /LIBPATH:
	obj_path_flag := /Fo:
	out_path_flag := /Fe:
	library_flag :=
	dynamic_flag := /MD
	static_flag := /MT
	shared_flag := /LD
	compile_only_flag := /c
	link_flag := /link
	pkg_config_syntax := --msvc-syntax
	obj_ext := .obj
	out_ext := .exe
endif

c_compiler := $(CC)
cpp_compiler := $(CXX)
c_compilation_flags := $(CFLAGS) $(dynamic_flag) `pkg-config $(pkg_config_syntax) --cflags gio-2.0`
cpp_compilation_flags := -Wall -std=c++20 -Ifltk/build -O2 -pthread $(dynamic_flag) `pkg-config $(pkg_config_syntax) --cflags gio-2.0`
link_time_flags := `fltk/build/fltk-config --use-images --ldstaticflags`
libraries := $(library_flag)xdo `pkg-config $(pkg_config_syntax) --libs gio-2.0`
prefix := /usr/local/bin

all: emoji-picker$(out_ext)
.PHONY: all

obj/theme_0$(obj_ext): ./theme.cpp .polybuild.mk ./theme.hpp ./glib.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@"$(cpp_compiler)" $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/main_0$(obj_ext): ./main.cpp .polybuild.mk ./emoji_data.hpp ./theme.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@"$(cpp_compiler)" $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

objects :=  obj/theme_0$(obj_ext) obj/main_0$(obj_ext)
emoji-picker$(out_ext): .polybuild.mk $(objects) $(static_libraries)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Building $@..."
	@"$(cpp_compiler)" $(objects) $(static_libraries) $(cpp_compilation_flags) $(out_path_flag)$@ $(link_flag) $(link_time_flags) $(libraries)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished building $@!"

clean:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Deleting emoji-picker$(out_ext) and obj..."
	@rm -rf emoji-picker$(out_ext) obj
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished deleting emoji-picker$(out_ext) and obj!"
.PHONY: clean

install:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Copying emoji-picker$(out_ext) to $(prefix)..."
	@cp emoji-picker$(out_ext) $(prefix)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished copying emoji-picker$(out_ext) to $(prefix)!"
.PHONY: install
